os: linux
dist: bionic
language: java
jdk: openjdk11
script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B
notifications:
  email:
    - thomas.woehlke@gmail.com