package org.woehlke.computer.kurzweil.tabs;

public enum TabType {

    CYCLIC_CELLULAR_AUTOMATON,
    DIFFUSION_LIMITED_AGGREGATION,
    SIMULATED_EVOLUTION,
    MANDELBROT_SET,
    RANDOM_WALK_WIENER_PROCESS,
    KOCH_SNOWFLAKE,
    SAME_GAME,
    SIERPINSKI_TRIANGLE,
    TETRIS,
    TURMITE,
    WATOR,
    CONWAYS_GAME_OF_LIFE
}
