theme: jekyll-theme-slate
title: Cyclic cellular automaton
description: The cyclic cellular automaton is a cellular automaton rule developed by David Griffeath and studied by several other cellular automaton researchers.