version: 2.1
jobs:
  build:
    docker:
      - image: buildpack-deps:cosmic
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            apt-get update
            apt-get upgrade -y
            echo 'Installing java, groovy and gradle!'
            apt-get install openjdk-8-jdk groovy gradle -y
      - checkout
      - run:
          name: Building Project
          command:  |
            echo 'running gradle build!'
            ./gradlew --max-workers 1 --continue build
            ./gradlew --max-workers 1 --continue jar