package org.woehlke.computer.kurzweil.apps;

public enum TabType {

    CYCLIC_CELLULAR_AUTOMATON,
    DIFFUSION_LIMITED_AGGREGATION,
    SIMULATED_EVOLUTION,
    MANDELBROT_SET,
    KOCH_SNOWFLAKE,
    SAME_GAME,
    SIERPINSKI_TRIANGLE,
    TETRIS,
    TURMITE,
    WATOR
}
